version: '3'

volumes:
  mysql_data:

services:
  api:
    build: ./docker/api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: chat
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev