version: '3'

volumes:
  mysql_data:
  node_modules_data:

services:
  api:
    build: ./docker/api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: node:latest
    volumes:
      - ./frontend:/app
      - node_modules_data:/app/node_modules
    tty: true
    working_dir: /app
    command: npm run serve
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: chat
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev